# Generated by Django 2.0.6 on 2018-06-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('traffic', models.CharField(max_length=300, null=True)),
                ('ldarea_low_lim', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('ldarea_cap', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('price_low_lim', models.IntegerField(default=0, null=True)),
                ('price_ceil', models.IntegerField(default=0, null=True)),
                ('buildcove', models.CharField(max_length=50, null=True)),
                ('geography', models.CharField(max_length=50, null=True)),
                ('usage_area', models.CharField(max_length=50, null=True)),
                ('cont_add', models.CharField(max_length=200, null=True)),
                ('cont_num', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(max_length=300)),
            ],
        ),
    ]
